---

server:
  port: 8003

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/attendee
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

